#!/bin/bash

rm -r ../source/build
mkdir ../source/build
cd ../source/build
cmake -DCMAKE_TOOLCHAIN_FILE=../../cross_compile/toolchain_win64.cmake ..
make
cp ranger.exe ../../ranger64.exe	
cd ../../cross_compile

rm -r ../source/build
mkdir ../source/build
cd ../source/build
cmake -DCMAKE_TOOLCHAIN_FILE=../../cross_compile/toolchain_win32.cmake ..
make
cp ranger.exe ../../ranger32.exe	
cd ../../cross_compile
