# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

compute_split_frequencies <- function(forest_object, max_depth) {
    .Call('_grf_compute_split_frequencies', PACKAGE = 'grf', forest_object, max_depth)
}

compute_weights <- function(forest_object, input_data, sparse_input_data, num_threads) {
    .Call('_grf_compute_weights', PACKAGE = 'grf', forest_object, input_data, sparse_input_data, num_threads)
}

compute_weights_oob <- function(forest_object, input_data, sparse_input_data, num_threads) {
    .Call('_grf_compute_weights_oob', PACKAGE = 'grf', forest_object, input_data, sparse_input_data, num_threads)
}

deserialize_tree <- function(forest_object, tree_index) {
    .Call('_grf_deserialize_tree', PACKAGE = 'grf', forest_object, tree_index)
}

custom_train <- function(input_data, sparse_input_data, outcome_index, mtry, num_trees, num_threads, min_node_size, sample_fraction, seed, honesty, ci_group_size, alpha, imbalance_penalty, clusters, samples_per_cluster) {
    .Call('_grf_custom_train', PACKAGE = 'grf', input_data, sparse_input_data, outcome_index, mtry, num_trees, num_threads, min_node_size, sample_fraction, seed, honesty, ci_group_size, alpha, imbalance_penalty, clusters, samples_per_cluster)
}

custom_predict <- function(forest_object, input_data, sparse_input_data, num_threads) {
    .Call('_grf_custom_predict', PACKAGE = 'grf', forest_object, input_data, sparse_input_data, num_threads)
}

custom_predict_oob <- function(forest_object, input_data, sparse_input_data, num_threads) {
    .Call('_grf_custom_predict_oob', PACKAGE = 'grf', forest_object, input_data, sparse_input_data, num_threads)
}

instrumental_train <- function(input_data, sparse_input_data, outcome_index, treatment_index, instrument_index, mtry, num_trees, num_threads, min_node_size, sample_fraction, seed, honesty, ci_group_size, reduced_form_weight, alpha, imbalance_penalty, stabilize_splits, clusters, samples_per_cluster) {
    .Call('_grf_instrumental_train', PACKAGE = 'grf', input_data, sparse_input_data, outcome_index, treatment_index, instrument_index, mtry, num_trees, num_threads, min_node_size, sample_fraction, seed, honesty, ci_group_size, reduced_form_weight, alpha, imbalance_penalty, stabilize_splits, clusters, samples_per_cluster)
}

instrumental_predict <- function(forest_object, input_data, sparse_input_data, num_threads, ci_group_size) {
    .Call('_grf_instrumental_predict', PACKAGE = 'grf', forest_object, input_data, sparse_input_data, num_threads, ci_group_size)
}

instrumental_predict_oob <- function(forest_object, input_data, sparse_input_data, num_threads, ci_group_size) {
    .Call('_grf_instrumental_predict_oob', PACKAGE = 'grf', forest_object, input_data, sparse_input_data, num_threads, ci_group_size)
}

quantile_train <- function(quantiles, regression_splits, input_data, sparse_input_data, outcome_index, mtry, num_trees, num_threads, min_node_size, sample_fraction, seed, honesty, ci_group_size, alpha, imbalance_penalty, clusters, samples_per_cluster) {
    .Call('_grf_quantile_train', PACKAGE = 'grf', quantiles, regression_splits, input_data, sparse_input_data, outcome_index, mtry, num_trees, num_threads, min_node_size, sample_fraction, seed, honesty, ci_group_size, alpha, imbalance_penalty, clusters, samples_per_cluster)
}

quantile_predict <- function(forest_object, quantiles, input_data, sparse_input_data, num_threads) {
    .Call('_grf_quantile_predict', PACKAGE = 'grf', forest_object, quantiles, input_data, sparse_input_data, num_threads)
}

quantile_predict_oob <- function(forest_object, quantiles, input_data, sparse_input_data, num_threads) {
    .Call('_grf_quantile_predict_oob', PACKAGE = 'grf', forest_object, quantiles, input_data, sparse_input_data, num_threads)
}

regression_train <- function(input_data, sparse_input_data, outcome_index, mtry, num_trees, num_threads, min_node_size, sample_fraction, seed, honesty, ci_group_size, alpha, imbalance_penalty, clusters, samples_per_cluster) {
    .Call('_grf_regression_train', PACKAGE = 'grf', input_data, sparse_input_data, outcome_index, mtry, num_trees, num_threads, min_node_size, sample_fraction, seed, honesty, ci_group_size, alpha, imbalance_penalty, clusters, samples_per_cluster)
}

regression_predict <- function(forest_object, input_data, sparse_input_data, num_threads, ci_group_size) {
    .Call('_grf_regression_predict', PACKAGE = 'grf', forest_object, input_data, sparse_input_data, num_threads, ci_group_size)
}

regression_predict_oob <- function(forest_object, input_data, sparse_input_data, num_threads, ci_group_size) {
    .Call('_grf_regression_predict_oob', PACKAGE = 'grf', forest_object, input_data, sparse_input_data, num_threads, ci_group_size)
}

local_linear_predict <- function(forest, input_data, training_data, sparse_input_data, sparse_training_data, lambda, use_unweighted_penalty, num_threads) {
    .Call('_grf_local_linear_predict', PACKAGE = 'grf', forest, input_data, training_data, sparse_input_data, sparse_training_data, lambda, use_unweighted_penalty, num_threads)
}

local_linear_predict_oob <- function(forest, input_data, sparse_input_data, lambda, use_unweighted_penalty, num_threads) {
    .Call('_grf_local_linear_predict_oob', PACKAGE = 'grf', forest, input_data, sparse_input_data, lambda, use_unweighted_penalty, num_threads)
}

