# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

quantile_train <- function(quantiles, input_data, outcome_index, sparse_data, variable_names, mtry, num_trees, verbose, num_threads, min_node_size, sample_with_replacement, keep_inbag, sample_fraction) {
    .Call('gradient_forest_quantile_train', PACKAGE = 'gradient.forest', quantiles, input_data, outcome_index, sparse_data, variable_names, mtry, num_trees, verbose, num_threads, min_node_size, sample_with_replacement, keep_inbag, sample_fraction)
}

quantile_predict <- function(forest, quantiles, input_data, sparse_data, variable_names, num_threads) {
    .Call('gradient_forest_quantile_predict', PACKAGE = 'gradient.forest', forest, quantiles, input_data, sparse_data, variable_names, num_threads)
}

