# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

instrumental_train <- function(input_data, outcome_index, treatment_index, instrument_index, sparse_data, variable_names, mtry, num_trees, verbose, num_threads, min_node_size, sample_with_replacement, keep_inbag, sample_fraction, no_split_variables, seed, honesty) {
    .Call('gradient_forest_instrumental_train', PACKAGE = 'gradient.forest', input_data, outcome_index, treatment_index, instrument_index, sparse_data, variable_names, mtry, num_trees, verbose, num_threads, min_node_size, sample_with_replacement, keep_inbag, sample_fraction, no_split_variables, seed, honesty)
}

instrumental_predict <- function(forest, input_data, sparse_data, variable_names, num_threads) {
    .Call('gradient_forest_instrumental_predict', PACKAGE = 'gradient.forest', forest, input_data, sparse_data, variable_names, num_threads)
}

instrumental_predict_oob <- function(forest, input_data, sparse_data, variable_names, num_threads) {
    .Call('gradient_forest_instrumental_predict_oob', PACKAGE = 'gradient.forest', forest, input_data, sparse_data, variable_names, num_threads)
}

quantile_train <- function(quantiles, input_data, outcome_index, sparse_data, variable_names, mtry, num_trees, verbose, num_threads, min_node_size, sample_with_replacement, keep_inbag, sample_fraction, no_split_variables, seed, honesty) {
    .Call('gradient_forest_quantile_train', PACKAGE = 'gradient.forest', quantiles, input_data, outcome_index, sparse_data, variable_names, mtry, num_trees, verbose, num_threads, min_node_size, sample_with_replacement, keep_inbag, sample_fraction, no_split_variables, seed, honesty)
}

quantile_predict <- function(forest, quantiles, input_data, sparse_data, variable_names, num_threads) {
    .Call('gradient_forest_quantile_predict', PACKAGE = 'gradient.forest', forest, quantiles, input_data, sparse_data, variable_names, num_threads)
}

quantile_predict_oob <- function(forest, quantiles, input_data, sparse_data, variable_names, num_threads) {
    .Call('gradient_forest_quantile_predict_oob', PACKAGE = 'gradient.forest', forest, quantiles, input_data, sparse_data, variable_names, num_threads)
}

regression_train <- function(input_data, outcome_index, sparse_data, variable_names, mtry, num_trees, verbose, num_threads, min_node_size, sample_with_replacement, keep_inbag, sample_fraction, no_split_variables, seed, honesty) {
    .Call('gradient_forest_regression_train', PACKAGE = 'gradient.forest', input_data, outcome_index, sparse_data, variable_names, mtry, num_trees, verbose, num_threads, min_node_size, sample_with_replacement, keep_inbag, sample_fraction, no_split_variables, seed, honesty)
}

regression_predict <- function(forest, input_data, sparse_data, variable_names, num_threads) {
    .Call('gradient_forest_regression_predict', PACKAGE = 'gradient.forest', forest, input_data, sparse_data, variable_names, num_threads)
}

regression_predict_oob <- function(forest, input_data, sparse_data, variable_names, num_threads) {
    .Call('gradient_forest_regression_predict_oob', PACKAGE = 'gradient.forest', forest, input_data, sparse_data, variable_names, num_threads)
}

